package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class MarketConference extends Model {
    /**
     * 自增id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * 显示图片
     *
     * @mbggenerated
     */
    private String imgPath;

    /**
     * 标题
     *
     * @mbggenerated
     */
    private String title;

    /**
     * 详情
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * 发布人id
     *
     * @mbggenerated
     */
    private Long publishPeopleId;

    /**
     * 发布时间
     *
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * 截止时间
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * 更新时间
     *
     * @mbggenerated
     */
    private Date rowUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_market_conference.id
     *
     * @return the value of n_market_conference.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "自增id")
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_market_conference.id
     *
     * @param id the value for n_market_conference.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_market_conference.img_path
     *
     * @return the value of n_market_conference.img_path
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "显示图片")
    public String getImgPath() {
        return imgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_market_conference.img_path
     *
     * @param imgPath the value for n_market_conference.img_path
     *
     * @mbggenerated
     */
    public void setImgPath(String imgPath) {
        this.imgPath = imgPath == null ? null : imgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_market_conference.title
     *
     * @return the value of n_market_conference.title
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "标题")
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_market_conference.title
     *
     * @param title the value for n_market_conference.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_market_conference.detail
     *
     * @return the value of n_market_conference.detail
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "详情")
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_market_conference.detail
     *
     * @param detail the value for n_market_conference.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_market_conference.publish_people_id
     *
     * @return the value of n_market_conference.publish_people_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "发布人id")
    public Long getPublishPeopleId() {
        return publishPeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_market_conference.publish_people_id
     *
     * @param publishPeopleId the value for n_market_conference.publish_people_id
     *
     * @mbggenerated
     */
    public void setPublishPeopleId(Long publishPeopleId) {
        this.publishPeopleId = publishPeopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_market_conference.row_add_time
     *
     * @return the value of n_market_conference.row_add_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "发布时间")
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_market_conference.row_add_time
     *
     * @param rowAddTime the value for n_market_conference.row_add_time
     *
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_market_conference.end_time
     *
     * @return the value of n_market_conference.end_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "截止时间")
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_market_conference.end_time
     *
     * @param endTime the value for n_market_conference.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_market_conference.row_update_time
     *
     * @return the value of n_market_conference.row_update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "更新时间")
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_market_conference.row_update_time
     *
     * @param rowUpdateTime the value for n_market_conference.row_update_time
     *
     * @mbggenerated
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }
}