package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class RecommendZan extends Model {

	/**
	 * 自增id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 特色推荐id
	 * @mbggenerated
	 */
	private Long recommendId;
	/**
	 * 点赞人id
	 * @mbggenerated
	 */
	private Long buserId;
	/**
	 * 添加时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 修改时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_recommend_zan.id
	 * @return  the value of n_recommend_zan.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_recommend_zan.id
	 * @param id  the value for n_recommend_zan.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_recommend_zan.recommend_id
	 * @return  the value of n_recommend_zan.recommend_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "特色推荐id")
	public Long getRecommendId() {
		return recommendId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_recommend_zan.recommend_id
	 * @param recommendId  the value for n_recommend_zan.recommend_id
	 * @mbggenerated
	 */
	public void setRecommendId(Long recommendId) {
		this.recommendId = recommendId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_recommend_zan.buser_id
	 * @return  the value of n_recommend_zan.buser_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "点赞人id")
	public Long getBuserId() {
		return buserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_recommend_zan.buser_id
	 * @param buserId  the value for n_recommend_zan.buser_id
	 * @mbggenerated
	 */
	public void setBuserId(Long buserId) {
		this.buserId = buserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_recommend_zan.row_add_time
	 * @return  the value of n_recommend_zan.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "添加时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_recommend_zan.row_add_time
	 * @param rowAddTime  the value for n_recommend_zan.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_recommend_zan.row_update_time
	 * @return  the value of n_recommend_zan.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "修改时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_recommend_zan.row_update_time
	 * @param rowUpdateTime  the value for n_recommend_zan.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}
}