package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class Activity extends Model {

	/**
	 * 自增id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 发布人id
	 * @mbggenerated
	 */
	private Long publishId;
	/**
	 * 小区id
	 * @mbggenerated
	 */
	private Long communtiyId;
	/**
	 * 活动图片
	 * @mbggenerated
	 */
	private String imgPath;
	/**
	 * 活动标题
	 * @mbggenerated
	 */
	private String title;
	/**
	 * 活动内容
	 * @mbggenerated
	 */
	private String content;
	/**
	 * 1：文娱活动,2：义工活动,3：关爱老人
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * 报名截止时间
	 * @mbggenerated
	 */
	private Date endTime;
	/**
	 * 发布时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 更新时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;
	/**
	 * 活动结束时间
	 * @mbggenerated
	 */
	private Date activityEndTime;
	/**
	 * 阅读数量
	 * @mbggenerated
	 */
	private Integer readCount;
	/**
	 * 是否置顶（0，否；1，是）
	 * @mbggenerated
	 */
	private Integer isTop;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.id
	 * @return  the value of n_activity.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.id
	 * @param id  the value for n_activity.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.publish_id
	 * @return  the value of n_activity.publish_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "发布人id")
	public Long getPublishId() {
		return publishId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.publish_id
	 * @param publishId  the value for n_activity.publish_id
	 * @mbggenerated
	 */
	public void setPublishId(Long publishId) {
		this.publishId = publishId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.communtiy_id
	 * @return  the value of n_activity.communtiy_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "小区id")
	public Long getCommuntiyId() {
		return communtiyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.communtiy_id
	 * @param communtiyId  the value for n_activity.communtiy_id
	 * @mbggenerated
	 */
	public void setCommuntiyId(Long communtiyId) {
		this.communtiyId = communtiyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.img_path
	 * @return  the value of n_activity.img_path
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "活动图片")
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.img_path
	 * @param imgPath  the value for n_activity.img_path
	 * @mbggenerated
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath == null ? null : imgPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.title
	 * @return  the value of n_activity.title
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "活动标题")
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.title
	 * @param title  the value for n_activity.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.content
	 * @return  the value of n_activity.content
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "活动内容")
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.content
	 * @param content  the value for n_activity.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.type
	 * @return  the value of n_activity.type
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "1：文娱活动,2：义工活动,3：关爱老人")
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.type
	 * @param type  the value for n_activity.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.end_time
	 * @return  the value of n_activity.end_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "报名截止时间")
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.end_time
	 * @param endTime  the value for n_activity.end_time
	 * @mbggenerated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.row_add_time
	 * @return  the value of n_activity.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "发布时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.row_add_time
	 * @param rowAddTime  the value for n_activity.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.row_update_time
	 * @return  the value of n_activity.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "更新时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.row_update_time
	 * @param rowUpdateTime  the value for n_activity.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.activity_end_time
	 * @return  the value of n_activity.activity_end_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "活动结束时间")
	public Date getActivityEndTime() {
		return activityEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.activity_end_time
	 * @param activityEndTime  the value for n_activity.activity_end_time
	 * @mbggenerated
	 */
	public void setActivityEndTime(Date activityEndTime) {
		this.activityEndTime = activityEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.read_count
	 * @return  the value of n_activity.read_count
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "阅读数量")
	public Integer getReadCount() {
		return readCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.read_count
	 * @param readCount  the value for n_activity.read_count
	 * @mbggenerated
	 */
	public void setReadCount(Integer readCount) {
		this.readCount = readCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_activity.is_top
	 * @return  the value of n_activity.is_top
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "是否置顶（0，否；1，是）")
	public Integer getIsTop() {
		return isTop;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_activity.is_top
	 * @param isTop  the value for n_activity.is_top
	 * @mbggenerated
	 */
	public void setIsTop(Integer isTop) {
		this.isTop = isTop;
	}
	
}