package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

public class BizUser extends Model implements Serializable{

	/**
	 * 自增id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 姓名
	 * @mbggenerated
	 */
	private String name;
	/**
	 * 昵称
	 * @mbggenerated
	 */
	private String nickname;
	/**
	 * 头像
	 * @mbggenerated
	 */
	private String headPortrait;
	/**
	 * 性别
	 * @mbggenerated
	 */
	private String sex;
	/**
	 * 手机
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * 密码
	 * @mbggenerated
	 */
	private String password;
	/**
	 * 状态，1启用，0禁用
	 * @mbggenerated
	 */
	private Short status;
	/**
	 * 当前绑定房产
	 * @mbggenerated
	 */
	private Long currentRoomId;
	/**
	 * 是否接受推送,0:不接受,1:接受
	 * @mbggenerated
	 */
	private Integer acceptPush;
	/**
	 * 积分
	 * @mbggenerated
	 */
	private Integer point;
	/**
	 * 添加时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 更新时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;
	/**
	 * 当前使用的客户端类型
	 * @mbggenerated
	 */
	private String phoneType;
	/**
	 * 小区id
	 * @mbggenerated
	 */
	private Long communityId;
	/**
	 * 设备id
	 * @mbggenerated
	 */
	private String registrationId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.id
	 * @return  the value of n_biz_user.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.id
	 * @param id  the value for n_biz_user.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.name
	 * @return  the value of n_biz_user.name
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "姓名")
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.name
	 * @param name  the value for n_biz_user.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.nickname
	 * @return  the value of n_biz_user.nickname
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "昵称")
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.nickname
	 * @param nickname  the value for n_biz_user.nickname
	 * @mbggenerated
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.head_portrait
	 * @return  the value of n_biz_user.head_portrait
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "头像")
	public String getHeadPortrait() {
		return headPortrait;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.head_portrait
	 * @param headPortrait  the value for n_biz_user.head_portrait
	 * @mbggenerated
	 */
	public void setHeadPortrait(String headPortrait) {
		this.headPortrait = headPortrait == null ? null : headPortrait.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.sex
	 * @return  the value of n_biz_user.sex
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "性别")
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.sex
	 * @param sex  the value for n_biz_user.sex
	 * @mbggenerated
	 */
	public void setSex(String sex) {
		this.sex = sex == null ? null : sex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.phone
	 * @return  the value of n_biz_user.phone
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "手机")
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.phone
	 * @param phone  the value for n_biz_user.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.password
	 * @return  the value of n_biz_user.password
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "密码")
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.password
	 * @param password  the value for n_biz_user.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.status
	 * @return  the value of n_biz_user.status
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "状态，1启用，0禁用")
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.status
	 * @param status  the value for n_biz_user.status
	 * @mbggenerated
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.current_room_id
	 * @return  the value of n_biz_user.current_room_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "当前绑定房产")
	public Long getCurrentRoomId() {
		return currentRoomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.current_room_id
	 * @param currentRoomId  the value for n_biz_user.current_room_id
	 * @mbggenerated
	 */
	public void setCurrentRoomId(Long currentRoomId) {
		this.currentRoomId = currentRoomId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.accept_push
	 * @return  the value of n_biz_user.accept_push
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "是否接受推送,0:不接受,1:接受")
	public Integer getAcceptPush() {
		return acceptPush;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.accept_push
	 * @param acceptPush  the value for n_biz_user.accept_push
	 * @mbggenerated
	 */
	public void setAcceptPush(Integer acceptPush) {
		this.acceptPush = acceptPush;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.point
	 * @return  the value of n_biz_user.point
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "积分")
	public Integer getPoint() {
		return point;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.point
	 * @param point  the value for n_biz_user.point
	 * @mbggenerated
	 */
	public void setPoint(Integer point) {
		this.point = point;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.row_add_time
	 * @return  the value of n_biz_user.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "添加时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.row_add_time
	 * @param rowAddTime  the value for n_biz_user.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.row_update_time
	 * @return  the value of n_biz_user.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "更新时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.row_update_time
	 * @param rowUpdateTime  the value for n_biz_user.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.phone_type
	 * @return  the value of n_biz_user.phone_type
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "当前使用的客户端类型")
	public String getPhoneType() {
		return phoneType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.phone_type
	 * @param phoneType  the value for n_biz_user.phone_type
	 * @mbggenerated
	 */
	public void setPhoneType(String phoneType) {
		this.phoneType = phoneType == null ? null : phoneType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.community_id
	 * @return  the value of n_biz_user.community_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "小区id")
	public Long getCommunityId() {
		return communityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.community_id
	 * @param communityId  the value for n_biz_user.community_id
	 * @mbggenerated
	 */
	public void setCommunityId(Long communityId) {
		this.communityId = communityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_biz_user.registration_id
	 * @return  the value of n_biz_user.registration_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "设备id")
	public String getRegistrationId() {
		return registrationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_biz_user.registration_id
	 * @param registrationId  the value for n_biz_user.registration_id
	 * @mbggenerated
	 */
	public void setRegistrationId(String registrationId) {
		this.registrationId = registrationId == null ? null : registrationId.trim();
	}

	private static final long serialVersionUID = 1L;
}