package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.ModelExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LinglingDeviceExample extends ModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public LinglingDeviceExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public Criteria getCriteria() {
		if (oredCriteria.size() == 0) {
			createCriteria();
		}
		return oredCriteria.get(0);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	public void addCriteria(List<Criterion> criteria) {
		getCriteria().getCriteria().addAll(criteria);
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table n_lingling_device
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;
		private boolean ignoreNull;

		private boolean isIgnoreNull() {
			return ignoreNull;
		}

		public Criteria ignoreNull() {
			this.ignoreNull = true;
			return (Criteria) this;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException(
							"Value for condition cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition));
			}
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException("Value for " + property
							+ " cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition, value));
			}
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException("Between values for " + property
							+ " cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition, value1, value2));
			}
		}

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userId is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userId is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("userId =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("userId <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("userId >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("userId >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("userId <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("userId <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("userId like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("userId not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("userId in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("userId not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("userId between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("userId not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andResidentialidIsNull() {
			addCriterion("residentialId is null");
			return (Criteria) this;
		}

		public Criteria andResidentialidIsNotNull() {
			addCriterion("residentialId is not null");
			return (Criteria) this;
		}

		public Criteria andResidentialidEqualTo(String value) {
			addCriterion("residentialId =", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidNotEqualTo(String value) {
			addCriterion("residentialId <>", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidGreaterThan(String value) {
			addCriterion("residentialId >", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidGreaterThanOrEqualTo(String value) {
			addCriterion("residentialId >=", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidLessThan(String value) {
			addCriterion("residentialId <", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidLessThanOrEqualTo(String value) {
			addCriterion("residentialId <=", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidLike(String value) {
			addCriterion("residentialId like", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidNotLike(String value) {
			addCriterion("residentialId not like", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidIn(List<String> values) {
			addCriterion("residentialId in", values, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidNotIn(List<String> values) {
			addCriterion("residentialId not in", values, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidBetween(String value1, String value2) {
			addCriterion("residentialId between", value1, value2,
					"residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidNotBetween(String value1, String value2) {
			addCriterion("residentialId not between", value1, value2,
					"residentialid");
			return (Criteria) this;
		}

		public Criteria andCustomtypeIsNull() {
			addCriterion("customType is null");
			return (Criteria) this;
		}

		public Criteria andCustomtypeIsNotNull() {
			addCriterion("customType is not null");
			return (Criteria) this;
		}

		public Criteria andCustomtypeEqualTo(String value) {
			addCriterion("customType =", value, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeNotEqualTo(String value) {
			addCriterion("customType <>", value, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeGreaterThan(String value) {
			addCriterion("customType >", value, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeGreaterThanOrEqualTo(String value) {
			addCriterion("customType >=", value, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeLessThan(String value) {
			addCriterion("customType <", value, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeLessThanOrEqualTo(String value) {
			addCriterion("customType <=", value, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeLike(String value) {
			addCriterion("customType like", value, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeNotLike(String value) {
			addCriterion("customType not like", value, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeIn(List<String> values) {
			addCriterion("customType in", values, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeNotIn(List<String> values) {
			addCriterion("customType not in", values, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeBetween(String value1, String value2) {
			addCriterion("customType between", value1, value2, "customtype");
			return (Criteria) this;
		}

		public Criteria andCustomtypeNotBetween(String value1, String value2) {
			addCriterion("customType not between", value1, value2, "customtype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeIsNull() {
			addCriterion("deviceType is null");
			return (Criteria) this;
		}

		public Criteria andDevicetypeIsNotNull() {
			addCriterion("deviceType is not null");
			return (Criteria) this;
		}

		public Criteria andDevicetypeEqualTo(String value) {
			addCriterion("deviceType =", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeNotEqualTo(String value) {
			addCriterion("deviceType <>", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeGreaterThan(String value) {
			addCriterion("deviceType >", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeGreaterThanOrEqualTo(String value) {
			addCriterion("deviceType >=", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeLessThan(String value) {
			addCriterion("deviceType <", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeLessThanOrEqualTo(String value) {
			addCriterion("deviceType <=", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeLike(String value) {
			addCriterion("deviceType like", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeNotLike(String value) {
			addCriterion("deviceType not like", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeIn(List<String> values) {
			addCriterion("deviceType in", values, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeNotIn(List<String> values) {
			addCriterion("deviceType not in", values, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeBetween(String value1, String value2) {
			addCriterion("deviceType between", value1, value2, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeNotBetween(String value1, String value2) {
			addCriterion("deviceType not between", value1, value2, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicecodeIsNull() {
			addCriterion("deviceCode is null");
			return (Criteria) this;
		}

		public Criteria andDevicecodeIsNotNull() {
			addCriterion("deviceCode is not null");
			return (Criteria) this;
		}

		public Criteria andDevicecodeEqualTo(String value) {
			addCriterion("deviceCode =", value, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeNotEqualTo(String value) {
			addCriterion("deviceCode <>", value, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeGreaterThan(String value) {
			addCriterion("deviceCode >", value, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeGreaterThanOrEqualTo(String value) {
			addCriterion("deviceCode >=", value, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeLessThan(String value) {
			addCriterion("deviceCode <", value, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeLessThanOrEqualTo(String value) {
			addCriterion("deviceCode <=", value, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeLike(String value) {
			addCriterion("deviceCode like", value, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeNotLike(String value) {
			addCriterion("deviceCode not like", value, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeIn(List<String> values) {
			addCriterion("deviceCode in", values, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeNotIn(List<String> values) {
			addCriterion("deviceCode not in", values, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeBetween(String value1, String value2) {
			addCriterion("deviceCode between", value1, value2, "devicecode");
			return (Criteria) this;
		}

		public Criteria andDevicecodeNotBetween(String value1, String value2) {
			addCriterion("deviceCode not between", value1, value2, "devicecode");
			return (Criteria) this;
		}

		public Criteria andLocktypeIsNull() {
			addCriterion("lockType is null");
			return (Criteria) this;
		}

		public Criteria andLocktypeIsNotNull() {
			addCriterion("lockType is not null");
			return (Criteria) this;
		}

		public Criteria andLocktypeEqualTo(String value) {
			addCriterion("lockType =", value, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeNotEqualTo(String value) {
			addCriterion("lockType <>", value, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeGreaterThan(String value) {
			addCriterion("lockType >", value, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeGreaterThanOrEqualTo(String value) {
			addCriterion("lockType >=", value, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeLessThan(String value) {
			addCriterion("lockType <", value, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeLessThanOrEqualTo(String value) {
			addCriterion("lockType <=", value, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeLike(String value) {
			addCriterion("lockType like", value, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeNotLike(String value) {
			addCriterion("lockType not like", value, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeIn(List<String> values) {
			addCriterion("lockType in", values, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeNotIn(List<String> values) {
			addCriterion("lockType not in", values, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeBetween(String value1, String value2) {
			addCriterion("lockType between", value1, value2, "locktype");
			return (Criteria) this;
		}

		public Criteria andLocktypeNotBetween(String value1, String value2) {
			addCriterion("lockType not between", value1, value2, "locktype");
			return (Criteria) this;
		}

		public Criteria andLockintervalIsNull() {
			addCriterion("lockInterval is null");
			return (Criteria) this;
		}

		public Criteria andLockintervalIsNotNull() {
			addCriterion("lockInterval is not null");
			return (Criteria) this;
		}

		public Criteria andLockintervalEqualTo(String value) {
			addCriterion("lockInterval =", value, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalNotEqualTo(String value) {
			addCriterion("lockInterval <>", value, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalGreaterThan(String value) {
			addCriterion("lockInterval >", value, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalGreaterThanOrEqualTo(String value) {
			addCriterion("lockInterval >=", value, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalLessThan(String value) {
			addCriterion("lockInterval <", value, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalLessThanOrEqualTo(String value) {
			addCriterion("lockInterval <=", value, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalLike(String value) {
			addCriterion("lockInterval like", value, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalNotLike(String value) {
			addCriterion("lockInterval not like", value, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalIn(List<String> values) {
			addCriterion("lockInterval in", values, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalNotIn(List<String> values) {
			addCriterion("lockInterval not in", values, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalBetween(String value1, String value2) {
			addCriterion("lockInterval between", value1, value2, "lockinterval");
			return (Criteria) this;
		}

		public Criteria andLockintervalNotBetween(String value1, String value2) {
			addCriterion("lockInterval not between", value1, value2,
					"lockinterval");
			return (Criteria) this;
		}

		public Criteria andDeviceidIsNull() {
			addCriterion("deviceId is null");
			return (Criteria) this;
		}

		public Criteria andDeviceidIsNotNull() {
			addCriterion("deviceId is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceidEqualTo(String value) {
			addCriterion("deviceId =", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotEqualTo(String value) {
			addCriterion("deviceId <>", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidGreaterThan(String value) {
			addCriterion("deviceId >", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidGreaterThanOrEqualTo(String value) {
			addCriterion("deviceId >=", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidLessThan(String value) {
			addCriterion("deviceId <", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidLessThanOrEqualTo(String value) {
			addCriterion("deviceId <=", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidLike(String value) {
			addCriterion("deviceId like", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotLike(String value) {
			addCriterion("deviceId not like", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidIn(List<String> values) {
			addCriterion("deviceId in", values, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotIn(List<String> values) {
			addCriterion("deviceId not in", values, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidBetween(String value1, String value2) {
			addCriterion("deviceId between", value1, value2, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotBetween(String value1, String value2) {
			addCriterion("deviceId not between", value1, value2, "deviceid");
			return (Criteria) this;
		}

		public Criteria andCommunityIdIsNull() {
			addCriterion("community_id is null");
			return (Criteria) this;
		}

		public Criteria andCommunityIdIsNotNull() {
			addCriterion("community_id is not null");
			return (Criteria) this;
		}

		public Criteria andCommunityIdEqualTo(Long value) {
			addCriterion("community_id =", value, "communityId");
			return (Criteria) this;
		}

		public Criteria andCommunityIdNotEqualTo(Long value) {
			addCriterion("community_id <>", value, "communityId");
			return (Criteria) this;
		}

		public Criteria andCommunityIdGreaterThan(Long value) {
			addCriterion("community_id >", value, "communityId");
			return (Criteria) this;
		}

		public Criteria andCommunityIdGreaterThanOrEqualTo(Long value) {
			addCriterion("community_id >=", value, "communityId");
			return (Criteria) this;
		}

		public Criteria andCommunityIdLessThan(Long value) {
			addCriterion("community_id <", value, "communityId");
			return (Criteria) this;
		}

		public Criteria andCommunityIdLessThanOrEqualTo(Long value) {
			addCriterion("community_id <=", value, "communityId");
			return (Criteria) this;
		}

		public Criteria andCommunityIdIn(List<Long> values) {
			addCriterion("community_id in", values, "communityId");
			return (Criteria) this;
		}

		public Criteria andCommunityIdNotIn(List<Long> values) {
			addCriterion("community_id not in", values, "communityId");
			return (Criteria) this;
		}

		public Criteria andCommunityIdBetween(Long value1, Long value2) {
			addCriterion("community_id between", value1, value2, "communityId");
			return (Criteria) this;
		}

		public Criteria andCommunityIdNotBetween(Long value1, Long value2) {
			addCriterion("community_id not between", value1, value2,
					"communityId");
			return (Criteria) this;
		}

		public Criteria andBuildingIdIsNull() {
			addCriterion("building_id is null");
			return (Criteria) this;
		}

		public Criteria andBuildingIdIsNotNull() {
			addCriterion("building_id is not null");
			return (Criteria) this;
		}

		public Criteria andBuildingIdEqualTo(Long value) {
			addCriterion("building_id =", value, "buildingId");
			return (Criteria) this;
		}

		public Criteria andBuildingIdNotEqualTo(Long value) {
			addCriterion("building_id <>", value, "buildingId");
			return (Criteria) this;
		}

		public Criteria andBuildingIdGreaterThan(Long value) {
			addCriterion("building_id >", value, "buildingId");
			return (Criteria) this;
		}

		public Criteria andBuildingIdGreaterThanOrEqualTo(Long value) {
			addCriterion("building_id >=", value, "buildingId");
			return (Criteria) this;
		}

		public Criteria andBuildingIdLessThan(Long value) {
			addCriterion("building_id <", value, "buildingId");
			return (Criteria) this;
		}

		public Criteria andBuildingIdLessThanOrEqualTo(Long value) {
			addCriterion("building_id <=", value, "buildingId");
			return (Criteria) this;
		}

		public Criteria andBuildingIdIn(List<Long> values) {
			addCriterion("building_id in", values, "buildingId");
			return (Criteria) this;
		}

		public Criteria andBuildingIdNotIn(List<Long> values) {
			addCriterion("building_id not in", values, "buildingId");
			return (Criteria) this;
		}

		public Criteria andBuildingIdBetween(Long value1, Long value2) {
			addCriterion("building_id between", value1, value2, "buildingId");
			return (Criteria) this;
		}

		public Criteria andBuildingIdNotBetween(Long value1, Long value2) {
			addCriterion("building_id not between", value1, value2,
					"buildingId");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeIsNull() {
			addCriterion("row_add_time is null");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeIsNotNull() {
			addCriterion("row_add_time is not null");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeEqualTo(Date value) {
			addCriterion("row_add_time =", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeNotEqualTo(Date value) {
			addCriterion("row_add_time <>", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeGreaterThan(Date value) {
			addCriterion("row_add_time >", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("row_add_time >=", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeLessThan(Date value) {
			addCriterion("row_add_time <", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("row_add_time <=", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeIn(List<Date> values) {
			addCriterion("row_add_time in", values, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeNotIn(List<Date> values) {
			addCriterion("row_add_time not in", values, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeBetween(Date value1, Date value2) {
			addCriterion("row_add_time between", value1, value2, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("row_add_time not between", value1, value2,
					"rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeIsNull() {
			addCriterion("row_update_time is null");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeIsNotNull() {
			addCriterion("row_update_time is not null");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeEqualTo(Date value) {
			addCriterion("row_update_time =", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeNotEqualTo(Date value) {
			addCriterion("row_update_time <>", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeGreaterThan(Date value) {
			addCriterion("row_update_time >", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("row_update_time >=", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeLessThan(Date value) {
			addCriterion("row_update_time <", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("row_update_time <=", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeIn(List<Date> values) {
			addCriterion("row_update_time in", values, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeNotIn(List<Date> values) {
			addCriterion("row_update_time not in", values, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("row_update_time between", value1, value2,
					"rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("row_update_time not between", value1, value2,
					"rowUpdateTime");
			return (Criteria) this;
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table n_lingling_device
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}