package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class AnnouncementSend extends Model {
    /**
     * 自增id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * 公告id
     *
     * @mbggenerated
     */
    private Long announcementId;

    /**
     * 接受人id
     *
     * @mbggenerated
     */
    private Long buserId;

    /**
     * 添加时间
     *
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * 更新时间
     *
     * @mbggenerated
     */
    private Date rowUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_announcement_send.id
     *
     * @return the value of n_announcement_send.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "自增id")
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_announcement_send.id
     *
     * @param id the value for n_announcement_send.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_announcement_send.announcement_id
     *
     * @return the value of n_announcement_send.announcement_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "公告id")
    public Long getAnnouncementId() {
        return announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_announcement_send.announcement_id
     *
     * @param announcementId the value for n_announcement_send.announcement_id
     *
     * @mbggenerated
     */
    public void setAnnouncementId(Long announcementId) {
        this.announcementId = announcementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_announcement_send.buser_id
     *
     * @return the value of n_announcement_send.buser_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "接受人id")
    public Long getBuserId() {
        return buserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_announcement_send.buser_id
     *
     * @param buserId the value for n_announcement_send.buser_id
     *
     * @mbggenerated
     */
    public void setBuserId(Long buserId) {
        this.buserId = buserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_announcement_send.row_add_time
     *
     * @return the value of n_announcement_send.row_add_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "添加时间")
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_announcement_send.row_add_time
     *
     * @param rowAddTime the value for n_announcement_send.row_add_time
     *
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_announcement_send.row_update_time
     *
     * @return the value of n_announcement_send.row_update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "更新时间")
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_announcement_send.row_update_time
     *
     * @param rowUpdateTime the value for n_announcement_send.row_update_time
     *
     * @mbggenerated
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }
}