package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class IndexesImg extends Model {

	/**
	 * 自增id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 图片路径
	 * @mbggenerated
	 */
	private String imgPath;
	/**
	 * 缩略图路径
	 * @mbggenerated
	 */
	private String imgPathThumbnail;
	/**
	 * 标题
	 * @mbggenerated
	 */
	private String title;
	/**
	 * 跳转地址
	 * @mbggenerated
	 */
	private String url;
	/**
	 * 1:服务+首页图片,2:尊享首页图片,3:邻里圈首页图片,4:app首页图片,5:首页推荐
	 * @mbggenerated
	 */
	private Integer type;
	/**
	 * 添加时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 修改时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;
	/**
	 * 小区ID
	 * @mbggenerated
	 */
	private Long communityId;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_indexes_img.id
	 * @return  the value of n_indexes_img.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_indexes_img.id
	 * @param id  the value for n_indexes_img.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_indexes_img.img_path
	 * @return  the value of n_indexes_img.img_path
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "图片路径")
	public String getImgPath() {
		return imgPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_indexes_img.img_path
	 * @param imgPath  the value for n_indexes_img.img_path
	 * @mbggenerated
	 */
	public void setImgPath(String imgPath) {
		this.imgPath = imgPath == null ? null : imgPath.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_indexes_img.img_path_thumbnail
	 * @return  the value of n_indexes_img.img_path_thumbnail
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "缩略图路径")
	public String getImgPathThumbnail() {
		return imgPathThumbnail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_indexes_img.img_path_thumbnail
	 * @param imgPathThumbnail  the value for n_indexes_img.img_path_thumbnail
	 * @mbggenerated
	 */
	public void setImgPathThumbnail(String imgPathThumbnail) {
		this.imgPathThumbnail = imgPathThumbnail == null ? null
				: imgPathThumbnail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_indexes_img.title
	 * @return  the value of n_indexes_img.title
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "标题")
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_indexes_img.title
	 * @param title  the value for n_indexes_img.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_indexes_img.url
	 * @return  the value of n_indexes_img.url
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "跳转地址")
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_indexes_img.url
	 * @param url  the value for n_indexes_img.url
	 * @mbggenerated
	 */
	public void setUrl(String url) {
		this.url = url == null ? null : url.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_indexes_img.type
	 * @return  the value of n_indexes_img.type
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "1:服务+首页图片,2:尊享首页图片,3:邻里圈首页图片,4:app首页图片,5:首页推荐")
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_indexes_img.type
	 * @param type  the value for n_indexes_img.type
	 * @mbggenerated
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_indexes_img.row_add_time
	 * @return  the value of n_indexes_img.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "添加时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_indexes_img.row_add_time
	 * @param rowAddTime  the value for n_indexes_img.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_indexes_img.row_update_time
	 * @return  the value of n_indexes_img.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "修改时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_indexes_img.row_update_time
	 * @param rowUpdateTime  the value for n_indexes_img.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_indexes_img.community_id
	 * @return  the value of n_indexes_img.community_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "小区ID")
	public Long getCommunityId() {
		return communityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_indexes_img.community_id
	 * @param communityId  the value for n_indexes_img.community_id
	 * @mbggenerated
	 */
	public void setCommunityId(Long communityId) {
		this.communityId = communityId;
	}

	// 自定义字段 小区名
	private String communityName;
	

	public String getCommunityName() {
		return communityName;
	}

	public void setCommunityName(String communityName) {
		this.communityName = communityName;
	}

	/**
	 * 自定义字段，后台页面使用
	 */
	private int urlType; // app 或 http链接
	private String appType; //类型 ： 邻里帮 。。。
	private String appTitle; //活动名称
	private Long appId; //活动名称
	
	
	public Long getAppId() {
		return appId;
	}

	public void setAppId(Long appId) {
		this.appId = appId;
	}

	public int getUrlType() {
		return urlType;
	}

	public void setUrlType(int urlType) {
		this.urlType = urlType;
	}

	public String getAppType() {
		return appType;
	}

	public void setAppType(String appType) {
		this.appType = appType;
	}

	public String getAppTitle() {
		return appTitle;
	}

	public void setAppTitle(String appTitle) {
		this.appTitle = appTitle;
	}
}