package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class LinglingServerAddr extends Model {

	/**
	 * 自增Id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 业主 Id
	 * @mbggenerated
	 */
	private String ownerid;
	/**
	 * 版本号（默认传入V2.0）
	 * @mbggenerated
	 */
	private String version;
	/**
	 * 服务器地址
	 * @mbggenerated
	 */
	private String addr;
	/**
	 * 访问服务器地址的令牌 
	 * @mbggenerated
	 */
	private String opentoken;
	/**
	 * 添加时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 修改时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_server_addr.id
	 * @return  the value of n_lingling_server_addr.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增Id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_server_addr.id
	 * @param id  the value for n_lingling_server_addr.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_server_addr.ownerId
	 * @return  the value of n_lingling_server_addr.ownerId
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "业主 Id")
	public String getOwnerid() {
		return ownerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_server_addr.ownerId
	 * @param ownerid  the value for n_lingling_server_addr.ownerId
	 * @mbggenerated
	 */
	public void setOwnerid(String ownerid) {
		this.ownerid = ownerid == null ? null : ownerid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_server_addr.version
	 * @return  the value of n_lingling_server_addr.version
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "版本号（默认传入V2.0）")
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_server_addr.version
	 * @param version  the value for n_lingling_server_addr.version
	 * @mbggenerated
	 */
	public void setVersion(String version) {
		this.version = version == null ? null : version.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_server_addr.addr
	 * @return  the value of n_lingling_server_addr.addr
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "服务器地址")
	public String getAddr() {
		return addr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_server_addr.addr
	 * @param addr  the value for n_lingling_server_addr.addr
	 * @mbggenerated
	 */
	public void setAddr(String addr) {
		this.addr = addr == null ? null : addr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_server_addr.openToken
	 * @return  the value of n_lingling_server_addr.openToken
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "访问服务器地址的令牌 ")
	public String getOpentoken() {
		return opentoken;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_server_addr.openToken
	 * @param opentoken  the value for n_lingling_server_addr.openToken
	 * @mbggenerated
	 */
	public void setOpentoken(String opentoken) {
		this.opentoken = opentoken == null ? null : opentoken.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_server_addr.row_add_time
	 * @return  the value of n_lingling_server_addr.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "添加时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_server_addr.row_add_time
	 * @param rowAddTime  the value for n_lingling_server_addr.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_server_addr.row_update_time
	 * @return  the value of n_lingling_server_addr.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "修改时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_server_addr.row_update_time
	 * @param rowUpdateTime  the value for n_lingling_server_addr.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}
}