package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.ModelExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LinglingOwnerExample extends ModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public LinglingOwnerExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public Criteria getCriteria() {
		if (oredCriteria.size() == 0) {
			createCriteria();
		}
		return oredCriteria.get(0);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	public void addCriteria(List<Criterion> criteria) {
		getCriteria().getCriteria().addAll(criteria);
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table n_lingling_owner
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;
		private boolean ignoreNull;

		private boolean isIgnoreNull() {
			return ignoreNull;
		}

		public Criteria ignoreNull() {
			this.ignoreNull = true;
			return (Criteria) this;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException(
							"Value for condition cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition));
			}
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException("Value for " + property
							+ " cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition, value));
			}
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException("Between values for " + property
							+ " cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition, value1, value2));
			}
		}

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("userId is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("userId is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(String value) {
			addCriterion("userId =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(String value) {
			addCriterion("userId <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(String value) {
			addCriterion("userId >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(String value) {
			addCriterion("userId >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(String value) {
			addCriterion("userId <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(String value) {
			addCriterion("userId <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLike(String value) {
			addCriterion("userId like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotLike(String value) {
			addCriterion("userId not like", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<String> values) {
			addCriterion("userId in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<String> values) {
			addCriterion("userId not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(String value1, String value2) {
			addCriterion("userId between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(String value1, String value2) {
			addCriterion("userId not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andOwnernameIsNull() {
			addCriterion("ownerName is null");
			return (Criteria) this;
		}

		public Criteria andOwnernameIsNotNull() {
			addCriterion("ownerName is not null");
			return (Criteria) this;
		}

		public Criteria andOwnernameEqualTo(String value) {
			addCriterion("ownerName =", value, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameNotEqualTo(String value) {
			addCriterion("ownerName <>", value, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameGreaterThan(String value) {
			addCriterion("ownerName >", value, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameGreaterThanOrEqualTo(String value) {
			addCriterion("ownerName >=", value, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameLessThan(String value) {
			addCriterion("ownerName <", value, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameLessThanOrEqualTo(String value) {
			addCriterion("ownerName <=", value, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameLike(String value) {
			addCriterion("ownerName like", value, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameNotLike(String value) {
			addCriterion("ownerName not like", value, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameIn(List<String> values) {
			addCriterion("ownerName in", values, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameNotIn(List<String> values) {
			addCriterion("ownerName not in", values, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameBetween(String value1, String value2) {
			addCriterion("ownerName between", value1, value2, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnernameNotBetween(String value1, String value2) {
			addCriterion("ownerName not between", value1, value2, "ownername");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneIsNull() {
			addCriterion("ownerTelephone is null");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneIsNotNull() {
			addCriterion("ownerTelephone is not null");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneEqualTo(String value) {
			addCriterion("ownerTelephone =", value, "ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneNotEqualTo(String value) {
			addCriterion("ownerTelephone <>", value, "ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneGreaterThan(String value) {
			addCriterion("ownerTelephone >", value, "ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneGreaterThanOrEqualTo(String value) {
			addCriterion("ownerTelephone >=", value, "ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneLessThan(String value) {
			addCriterion("ownerTelephone <", value, "ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneLessThanOrEqualTo(String value) {
			addCriterion("ownerTelephone <=", value, "ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneLike(String value) {
			addCriterion("ownerTelephone like", value, "ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneNotLike(String value) {
			addCriterion("ownerTelephone not like", value, "ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneIn(List<String> values) {
			addCriterion("ownerTelephone in", values, "ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneNotIn(List<String> values) {
			addCriterion("ownerTelephone not in", values, "ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneBetween(String value1, String value2) {
			addCriterion("ownerTelephone between", value1, value2,
					"ownertelephone");
			return (Criteria) this;
		}

		public Criteria andOwnertelephoneNotBetween(String value1, String value2) {
			addCriterion("ownerTelephone not between", value1, value2,
					"ownertelephone");
			return (Criteria) this;
		}

		public Criteria andMacIsNull() {
			addCriterion("mac is null");
			return (Criteria) this;
		}

		public Criteria andMacIsNotNull() {
			addCriterion("mac is not null");
			return (Criteria) this;
		}

		public Criteria andMacEqualTo(String value) {
			addCriterion("mac =", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacNotEqualTo(String value) {
			addCriterion("mac <>", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacGreaterThan(String value) {
			addCriterion("mac >", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacGreaterThanOrEqualTo(String value) {
			addCriterion("mac >=", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacLessThan(String value) {
			addCriterion("mac <", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacLessThanOrEqualTo(String value) {
			addCriterion("mac <=", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacLike(String value) {
			addCriterion("mac like", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacNotLike(String value) {
			addCriterion("mac not like", value, "mac");
			return (Criteria) this;
		}

		public Criteria andMacIn(List<String> values) {
			addCriterion("mac in", values, "mac");
			return (Criteria) this;
		}

		public Criteria andMacNotIn(List<String> values) {
			addCriterion("mac not in", values, "mac");
			return (Criteria) this;
		}

		public Criteria andMacBetween(String value1, String value2) {
			addCriterion("mac between", value1, value2, "mac");
			return (Criteria) this;
		}

		public Criteria andMacNotBetween(String value1, String value2) {
			addCriterion("mac not between", value1, value2, "mac");
			return (Criteria) this;
		}

		public Criteria andDeviceidsIsNull() {
			addCriterion("deviceIds is null");
			return (Criteria) this;
		}

		public Criteria andDeviceidsIsNotNull() {
			addCriterion("deviceIds is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceidsEqualTo(String value) {
			addCriterion("deviceIds =", value, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsNotEqualTo(String value) {
			addCriterion("deviceIds <>", value, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsGreaterThan(String value) {
			addCriterion("deviceIds >", value, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsGreaterThanOrEqualTo(String value) {
			addCriterion("deviceIds >=", value, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsLessThan(String value) {
			addCriterion("deviceIds <", value, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsLessThanOrEqualTo(String value) {
			addCriterion("deviceIds <=", value, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsLike(String value) {
			addCriterion("deviceIds like", value, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsNotLike(String value) {
			addCriterion("deviceIds not like", value, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsIn(List<String> values) {
			addCriterion("deviceIds in", values, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsNotIn(List<String> values) {
			addCriterion("deviceIds not in", values, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsBetween(String value1, String value2) {
			addCriterion("deviceIds between", value1, value2, "deviceids");
			return (Criteria) this;
		}

		public Criteria andDeviceidsNotBetween(String value1, String value2) {
			addCriterion("deviceIds not between", value1, value2, "deviceids");
			return (Criteria) this;
		}

		public Criteria andResidentialidIsNull() {
			addCriterion("residentialId is null");
			return (Criteria) this;
		}

		public Criteria andResidentialidIsNotNull() {
			addCriterion("residentialId is not null");
			return (Criteria) this;
		}

		public Criteria andResidentialidEqualTo(String value) {
			addCriterion("residentialId =", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidNotEqualTo(String value) {
			addCriterion("residentialId <>", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidGreaterThan(String value) {
			addCriterion("residentialId >", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidGreaterThanOrEqualTo(String value) {
			addCriterion("residentialId >=", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidLessThan(String value) {
			addCriterion("residentialId <", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidLessThanOrEqualTo(String value) {
			addCriterion("residentialId <=", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidLike(String value) {
			addCriterion("residentialId like", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidNotLike(String value) {
			addCriterion("residentialId not like", value, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidIn(List<String> values) {
			addCriterion("residentialId in", values, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidNotIn(List<String> values) {
			addCriterion("residentialId not in", values, "residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidBetween(String value1, String value2) {
			addCriterion("residentialId between", value1, value2,
					"residentialid");
			return (Criteria) this;
		}

		public Criteria andResidentialidNotBetween(String value1, String value2) {
			addCriterion("residentialId not between", value1, value2,
					"residentialid");
			return (Criteria) this;
		}

		public Criteria andRegcodeIsNull() {
			addCriterion("regcode is null");
			return (Criteria) this;
		}

		public Criteria andRegcodeIsNotNull() {
			addCriterion("regcode is not null");
			return (Criteria) this;
		}

		public Criteria andRegcodeEqualTo(String value) {
			addCriterion("regcode =", value, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeNotEqualTo(String value) {
			addCriterion("regcode <>", value, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeGreaterThan(String value) {
			addCriterion("regcode >", value, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeGreaterThanOrEqualTo(String value) {
			addCriterion("regcode >=", value, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeLessThan(String value) {
			addCriterion("regcode <", value, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeLessThanOrEqualTo(String value) {
			addCriterion("regcode <=", value, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeLike(String value) {
			addCriterion("regcode like", value, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeNotLike(String value) {
			addCriterion("regcode not like", value, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeIn(List<String> values) {
			addCriterion("regcode in", values, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeNotIn(List<String> values) {
			addCriterion("regcode not in", values, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeBetween(String value1, String value2) {
			addCriterion("regcode between", value1, value2, "regcode");
			return (Criteria) this;
		}

		public Criteria andRegcodeNotBetween(String value1, String value2) {
			addCriterion("regcode not between", value1, value2, "regcode");
			return (Criteria) this;
		}

		public Criteria andOwneridIsNull() {
			addCriterion("ownerId is null");
			return (Criteria) this;
		}

		public Criteria andOwneridIsNotNull() {
			addCriterion("ownerId is not null");
			return (Criteria) this;
		}

		public Criteria andOwneridEqualTo(String value) {
			addCriterion("ownerId =", value, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridNotEqualTo(String value) {
			addCriterion("ownerId <>", value, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridGreaterThan(String value) {
			addCriterion("ownerId >", value, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridGreaterThanOrEqualTo(String value) {
			addCriterion("ownerId >=", value, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridLessThan(String value) {
			addCriterion("ownerId <", value, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridLessThanOrEqualTo(String value) {
			addCriterion("ownerId <=", value, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridLike(String value) {
			addCriterion("ownerId like", value, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridNotLike(String value) {
			addCriterion("ownerId not like", value, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridIn(List<String> values) {
			addCriterion("ownerId in", values, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridNotIn(List<String> values) {
			addCriterion("ownerId not in", values, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridBetween(String value1, String value2) {
			addCriterion("ownerId between", value1, value2, "ownerid");
			return (Criteria) this;
		}

		public Criteria andOwneridNotBetween(String value1, String value2) {
			addCriterion("ownerId not between", value1, value2, "ownerid");
			return (Criteria) this;
		}

		public Criteria andResidentialnameIsNull() {
			addCriterion("residentialName is null");
			return (Criteria) this;
		}

		public Criteria andResidentialnameIsNotNull() {
			addCriterion("residentialName is not null");
			return (Criteria) this;
		}

		public Criteria andResidentialnameEqualTo(String value) {
			addCriterion("residentialName =", value, "residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameNotEqualTo(String value) {
			addCriterion("residentialName <>", value, "residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameGreaterThan(String value) {
			addCriterion("residentialName >", value, "residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameGreaterThanOrEqualTo(String value) {
			addCriterion("residentialName >=", value, "residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameLessThan(String value) {
			addCriterion("residentialName <", value, "residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameLessThanOrEqualTo(String value) {
			addCriterion("residentialName <=", value, "residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameLike(String value) {
			addCriterion("residentialName like", value, "residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameNotLike(String value) {
			addCriterion("residentialName not like", value, "residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameIn(List<String> values) {
			addCriterion("residentialName in", values, "residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameNotIn(List<String> values) {
			addCriterion("residentialName not in", values, "residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameBetween(String value1, String value2) {
			addCriterion("residentialName between", value1, value2,
					"residentialname");
			return (Criteria) this;
		}

		public Criteria andResidentialnameNotBetween(String value1,
				String value2) {
			addCriterion("residentialName not between", value1, value2,
					"residentialname");
			return (Criteria) this;
		}

		public Criteria andDeviceidIsNull() {
			addCriterion("deviceId is null");
			return (Criteria) this;
		}

		public Criteria andDeviceidIsNotNull() {
			addCriterion("deviceId is not null");
			return (Criteria) this;
		}

		public Criteria andDeviceidEqualTo(String value) {
			addCriterion("deviceId =", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotEqualTo(String value) {
			addCriterion("deviceId <>", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidGreaterThan(String value) {
			addCriterion("deviceId >", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidGreaterThanOrEqualTo(String value) {
			addCriterion("deviceId >=", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidLessThan(String value) {
			addCriterion("deviceId <", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidLessThanOrEqualTo(String value) {
			addCriterion("deviceId <=", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidLike(String value) {
			addCriterion("deviceId like", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotLike(String value) {
			addCriterion("deviceId not like", value, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidIn(List<String> values) {
			addCriterion("deviceId in", values, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotIn(List<String> values) {
			addCriterion("deviceId not in", values, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidBetween(String value1, String value2) {
			addCriterion("deviceId between", value1, value2, "deviceid");
			return (Criteria) this;
		}

		public Criteria andDeviceidNotBetween(String value1, String value2) {
			addCriterion("deviceId not between", value1, value2, "deviceid");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andDevicetypeIsNull() {
			addCriterion("deviceType is null");
			return (Criteria) this;
		}

		public Criteria andDevicetypeIsNotNull() {
			addCriterion("deviceType is not null");
			return (Criteria) this;
		}

		public Criteria andDevicetypeEqualTo(String value) {
			addCriterion("deviceType =", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeNotEqualTo(String value) {
			addCriterion("deviceType <>", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeGreaterThan(String value) {
			addCriterion("deviceType >", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeGreaterThanOrEqualTo(String value) {
			addCriterion("deviceType >=", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeLessThan(String value) {
			addCriterion("deviceType <", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeLessThanOrEqualTo(String value) {
			addCriterion("deviceType <=", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeLike(String value) {
			addCriterion("deviceType like", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeNotLike(String value) {
			addCriterion("deviceType not like", value, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeIn(List<String> values) {
			addCriterion("deviceType in", values, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeNotIn(List<String> values) {
			addCriterion("deviceType not in", values, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeBetween(String value1, String value2) {
			addCriterion("deviceType between", value1, value2, "devicetype");
			return (Criteria) this;
		}

		public Criteria andDevicetypeNotBetween(String value1, String value2) {
			addCriterion("deviceType not between", value1, value2, "devicetype");
			return (Criteria) this;
		}

		public Criteria andEncryptstrIsNull() {
			addCriterion("encryptStr is null");
			return (Criteria) this;
		}

		public Criteria andEncryptstrIsNotNull() {
			addCriterion("encryptStr is not null");
			return (Criteria) this;
		}

		public Criteria andEncryptstrEqualTo(String value) {
			addCriterion("encryptStr =", value, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrNotEqualTo(String value) {
			addCriterion("encryptStr <>", value, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrGreaterThan(String value) {
			addCriterion("encryptStr >", value, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrGreaterThanOrEqualTo(String value) {
			addCriterion("encryptStr >=", value, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrLessThan(String value) {
			addCriterion("encryptStr <", value, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrLessThanOrEqualTo(String value) {
			addCriterion("encryptStr <=", value, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrLike(String value) {
			addCriterion("encryptStr like", value, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrNotLike(String value) {
			addCriterion("encryptStr not like", value, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrIn(List<String> values) {
			addCriterion("encryptStr in", values, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrNotIn(List<String> values) {
			addCriterion("encryptStr not in", values, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrBetween(String value1, String value2) {
			addCriterion("encryptStr between", value1, value2, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andEncryptstrNotBetween(String value1, String value2) {
			addCriterion("encryptStr not between", value1, value2, "encryptstr");
			return (Criteria) this;
		}

		public Criteria andAddrIsNull() {
			addCriterion("addr is null");
			return (Criteria) this;
		}

		public Criteria andAddrIsNotNull() {
			addCriterion("addr is not null");
			return (Criteria) this;
		}

		public Criteria andAddrEqualTo(String value) {
			addCriterion("addr =", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotEqualTo(String value) {
			addCriterion("addr <>", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrGreaterThan(String value) {
			addCriterion("addr >", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrGreaterThanOrEqualTo(String value) {
			addCriterion("addr >=", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrLessThan(String value) {
			addCriterion("addr <", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrLessThanOrEqualTo(String value) {
			addCriterion("addr <=", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrLike(String value) {
			addCriterion("addr like", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotLike(String value) {
			addCriterion("addr not like", value, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrIn(List<String> values) {
			addCriterion("addr in", values, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotIn(List<String> values) {
			addCriterion("addr not in", values, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrBetween(String value1, String value2) {
			addCriterion("addr between", value1, value2, "addr");
			return (Criteria) this;
		}

		public Criteria andAddrNotBetween(String value1, String value2) {
			addCriterion("addr not between", value1, value2, "addr");
			return (Criteria) this;
		}

		public Criteria andOpentokenIsNull() {
			addCriterion("openToken is null");
			return (Criteria) this;
		}

		public Criteria andOpentokenIsNotNull() {
			addCriterion("openToken is not null");
			return (Criteria) this;
		}

		public Criteria andOpentokenEqualTo(String value) {
			addCriterion("openToken =", value, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenNotEqualTo(String value) {
			addCriterion("openToken <>", value, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenGreaterThan(String value) {
			addCriterion("openToken >", value, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenGreaterThanOrEqualTo(String value) {
			addCriterion("openToken >=", value, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenLessThan(String value) {
			addCriterion("openToken <", value, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenLessThanOrEqualTo(String value) {
			addCriterion("openToken <=", value, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenLike(String value) {
			addCriterion("openToken like", value, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenNotLike(String value) {
			addCriterion("openToken not like", value, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenIn(List<String> values) {
			addCriterion("openToken in", values, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenNotIn(List<String> values) {
			addCriterion("openToken not in", values, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenBetween(String value1, String value2) {
			addCriterion("openToken between", value1, value2, "opentoken");
			return (Criteria) this;
		}

		public Criteria andOpentokenNotBetween(String value1, String value2) {
			addCriterion("openToken not between", value1, value2, "opentoken");
			return (Criteria) this;
		}

		public Criteria andBuserIdIsNull() {
			addCriterion("buser_id is null");
			return (Criteria) this;
		}

		public Criteria andBuserIdIsNotNull() {
			addCriterion("buser_id is not null");
			return (Criteria) this;
		}

		public Criteria andBuserIdEqualTo(Long value) {
			addCriterion("buser_id =", value, "buserId");
			return (Criteria) this;
		}

		public Criteria andBuserIdNotEqualTo(Long value) {
			addCriterion("buser_id <>", value, "buserId");
			return (Criteria) this;
		}

		public Criteria andBuserIdGreaterThan(Long value) {
			addCriterion("buser_id >", value, "buserId");
			return (Criteria) this;
		}

		public Criteria andBuserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("buser_id >=", value, "buserId");
			return (Criteria) this;
		}

		public Criteria andBuserIdLessThan(Long value) {
			addCriterion("buser_id <", value, "buserId");
			return (Criteria) this;
		}

		public Criteria andBuserIdLessThanOrEqualTo(Long value) {
			addCriterion("buser_id <=", value, "buserId");
			return (Criteria) this;
		}

		public Criteria andBuserIdIn(List<Long> values) {
			addCriterion("buser_id in", values, "buserId");
			return (Criteria) this;
		}

		public Criteria andBuserIdNotIn(List<Long> values) {
			addCriterion("buser_id not in", values, "buserId");
			return (Criteria) this;
		}

		public Criteria andBuserIdBetween(Long value1, Long value2) {
			addCriterion("buser_id between", value1, value2, "buserId");
			return (Criteria) this;
		}

		public Criteria andBuserIdNotBetween(Long value1, Long value2) {
			addCriterion("buser_id not between", value1, value2, "buserId");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeIsNull() {
			addCriterion("row_add_time is null");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeIsNotNull() {
			addCriterion("row_add_time is not null");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeEqualTo(Date value) {
			addCriterion("row_add_time =", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeNotEqualTo(Date value) {
			addCriterion("row_add_time <>", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeGreaterThan(Date value) {
			addCriterion("row_add_time >", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("row_add_time >=", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeLessThan(Date value) {
			addCriterion("row_add_time <", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("row_add_time <=", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeIn(List<Date> values) {
			addCriterion("row_add_time in", values, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeNotIn(List<Date> values) {
			addCriterion("row_add_time not in", values, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeBetween(Date value1, Date value2) {
			addCriterion("row_add_time between", value1, value2, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("row_add_time not between", value1, value2,
					"rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeIsNull() {
			addCriterion("row_update_time is null");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeIsNotNull() {
			addCriterion("row_update_time is not null");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeEqualTo(Date value) {
			addCriterion("row_update_time =", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeNotEqualTo(Date value) {
			addCriterion("row_update_time <>", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeGreaterThan(Date value) {
			addCriterion("row_update_time >", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("row_update_time >=", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeLessThan(Date value) {
			addCriterion("row_update_time <", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("row_update_time <=", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeIn(List<Date> values) {
			addCriterion("row_update_time in", values, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeNotIn(List<Date> values) {
			addCriterion("row_update_time not in", values, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("row_update_time between", value1, value2,
					"rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("row_update_time not between", value1, value2,
					"rowUpdateTime");
			return (Criteria) this;
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table n_lingling_owner
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}