package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class LinglingDevice extends Model {

	/**
	 * 自增Id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 工程人员id
	 * @mbggenerated
	 */
	private String userid;
	/**
	 * 设备名称
	 * @mbggenerated
	 */
	private String name;
	/**
	 * 小区 ID
	 * @mbggenerated
	 */
	private String residentialid;
	/**
	 * 安装的类型（1为单元门，2 为公共门）
	 * @mbggenerated
	 */
	private String customtype;
	/**
	 * 设备类型（在1.1.3版本中可以不填）
	 * @mbggenerated
	 */
	private String devicetype;
	/**
	 * 设备串码 
	 * @mbggenerated
	 */
	private String devicecode;
	/**
	 * 锁的类型（0为电磁锁，1为电插锁）
	 * @mbggenerated
	 */
	private String locktype;
	/**
	 * 开门后多少秒关闭
	 * @mbggenerated
	 */
	private String lockinterval;
	/**
	 * 设备id（设备标志位，添加业主时使用）
	 * @mbggenerated
	 */
	private String deviceid;
	/**
	 * 小区Id
	 * @mbggenerated
	 */
	private Long communityId;
	/**
	 * 楼栋id,小区公共门为空或者小于0
	 * @mbggenerated
	 */
	private Long buildingId;
	/**
	 * 添加时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 修改时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.id
	 * @return  the value of n_lingling_device.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增Id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.id
	 * @param id  the value for n_lingling_device.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.userId
	 * @return  the value of n_lingling_device.userId
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "工程人员id")
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.userId
	 * @param userid  the value for n_lingling_device.userId
	 * @mbggenerated
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.name
	 * @return  the value of n_lingling_device.name
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "设备名称")
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.name
	 * @param name  the value for n_lingling_device.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.residentialId
	 * @return  the value of n_lingling_device.residentialId
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "小区 ID")
	public String getResidentialid() {
		return residentialid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.residentialId
	 * @param residentialid  the value for n_lingling_device.residentialId
	 * @mbggenerated
	 */
	public void setResidentialid(String residentialid) {
		this.residentialid = residentialid == null ? null : residentialid
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.customType
	 * @return  the value of n_lingling_device.customType
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "安装的类型（1为单元门，2 为公共门）")
	public String getCustomtype() {
		return customtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.customType
	 * @param customtype  the value for n_lingling_device.customType
	 * @mbggenerated
	 */
	public void setCustomtype(String customtype) {
		this.customtype = customtype == null ? null : customtype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.deviceType
	 * @return  the value of n_lingling_device.deviceType
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "设备类型（在1.1.3版本中可以不填）")
	public String getDevicetype() {
		return devicetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.deviceType
	 * @param devicetype  the value for n_lingling_device.deviceType
	 * @mbggenerated
	 */
	public void setDevicetype(String devicetype) {
		this.devicetype = devicetype == null ? null : devicetype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.deviceCode
	 * @return  the value of n_lingling_device.deviceCode
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "设备串码 ")
	public String getDevicecode() {
		return devicecode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.deviceCode
	 * @param devicecode  the value for n_lingling_device.deviceCode
	 * @mbggenerated
	 */
	public void setDevicecode(String devicecode) {
		this.devicecode = devicecode == null ? null : devicecode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.lockType
	 * @return  the value of n_lingling_device.lockType
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "锁的类型（0为电磁锁，1为电插锁）")
	public String getLocktype() {
		return locktype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.lockType
	 * @param locktype  the value for n_lingling_device.lockType
	 * @mbggenerated
	 */
	public void setLocktype(String locktype) {
		this.locktype = locktype == null ? null : locktype.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.lockInterval
	 * @return  the value of n_lingling_device.lockInterval
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "开门后多少秒关闭")
	public String getLockinterval() {
		return lockinterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.lockInterval
	 * @param lockinterval  the value for n_lingling_device.lockInterval
	 * @mbggenerated
	 */
	public void setLockinterval(String lockinterval) {
		this.lockinterval = lockinterval == null ? null : lockinterval.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.deviceId
	 * @return  the value of n_lingling_device.deviceId
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "设备id（设备标志位，添加业主时使用）")
	public String getDeviceid() {
		return deviceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.deviceId
	 * @param deviceid  the value for n_lingling_device.deviceId
	 * @mbggenerated
	 */
	public void setDeviceid(String deviceid) {
		this.deviceid = deviceid == null ? null : deviceid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.community_id
	 * @return  the value of n_lingling_device.community_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "小区Id")
	public Long getCommunityId() {
		return communityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.community_id
	 * @param communityId  the value for n_lingling_device.community_id
	 * @mbggenerated
	 */
	public void setCommunityId(Long communityId) {
		this.communityId = communityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.building_id
	 * @return  the value of n_lingling_device.building_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "楼栋id,小区公共门为空或者小于0")
	public Long getBuildingId() {
		return buildingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.building_id
	 * @param buildingId  the value for n_lingling_device.building_id
	 * @mbggenerated
	 */
	public void setBuildingId(Long buildingId) {
		this.buildingId = buildingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.row_add_time
	 * @return  the value of n_lingling_device.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "添加时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.row_add_time
	 * @param rowAddTime  the value for n_lingling_device.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_device.row_update_time
	 * @return  the value of n_lingling_device.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "修改时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_device.row_update_time
	 * @param rowUpdateTime  the value for n_lingling_device.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}
}