package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class NotifySend extends Model {

	/**
	 * 自增id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 消息通知id
	 * @mbggenerated
	 */
	private Long notifyId;
	/**
	 * 接受人id
	 * @mbggenerated
	 */
	private Long buserId;
	/**
	 * 是否已读,0：未读，1：已读
	 * @mbggenerated
	 */
	private Integer status;
	/**
	 * 添加时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 更新时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_notify_send.id
	 * @return  the value of n_notify_send.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_notify_send.id
	 * @param id  the value for n_notify_send.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_notify_send.notify_id
	 * @return  the value of n_notify_send.notify_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "消息通知id")
	public Long getNotifyId() {
		return notifyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_notify_send.notify_id
	 * @param notifyId  the value for n_notify_send.notify_id
	 * @mbggenerated
	 */
	public void setNotifyId(Long notifyId) {
		this.notifyId = notifyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_notify_send.buser_id
	 * @return  the value of n_notify_send.buser_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "接受人id")
	public Long getBuserId() {
		return buserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_notify_send.buser_id
	 * @param buserId  the value for n_notify_send.buser_id
	 * @mbggenerated
	 */
	public void setBuserId(Long buserId) {
		this.buserId = buserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_notify_send.status
	 * @return  the value of n_notify_send.status
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "是否已读,0：未读，1：已读")
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_notify_send.status
	 * @param status  the value for n_notify_send.status
	 * @mbggenerated
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_notify_send.row_add_time
	 * @return  the value of n_notify_send.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "添加时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_notify_send.row_add_time
	 * @param rowAddTime  the value for n_notify_send.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_notify_send.row_update_time
	 * @return  the value of n_notify_send.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "更新时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_notify_send.row_update_time
	 * @param rowUpdateTime  the value for n_notify_send.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}
}