package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class RoleResource extends Model {

	/**
	 * 自增id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 自增id
	 * @mbggenerated
	 */
	private Integer roleId;
	/**
	 * 资源ID
	 * @mbggenerated
	 */
	private Long resourceId;
	/**
	 * 添加时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 更新时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;
	/**
	 * 备注
	 * @mbggenerated
	 */
	private String roleNote;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_role_resource.id
	 * @return  the value of n_role_resource.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_role_resource.id
	 * @param id  the value for n_role_resource.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_role_resource.role_id
	 * @return  the value of n_role_resource.role_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增id")
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_role_resource.role_id
	 * @param roleId  the value for n_role_resource.role_id
	 * @mbggenerated
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_role_resource.resource_id
	 * @return  the value of n_role_resource.resource_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "资源ID")
	public Long getResourceId() {
		return resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_role_resource.resource_id
	 * @param resourceId  the value for n_role_resource.resource_id
	 * @mbggenerated
	 */
	public void setResourceId(Long resourceId) {
		this.resourceId = resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_role_resource.row_add_time
	 * @return  the value of n_role_resource.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "添加时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_role_resource.row_add_time
	 * @param rowAddTime  the value for n_role_resource.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_role_resource.row_update_time
	 * @return  the value of n_role_resource.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "更新时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_role_resource.row_update_time
	 * @param rowUpdateTime  the value for n_role_resource.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_role_resource.role_note
	 * @return  the value of n_role_resource.role_note
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "备注")
	public String getRoleNote() {
		return roleNote;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_role_resource.role_note
	 * @param roleNote  the value for n_role_resource.role_note
	 * @mbggenerated
	 */
	public void setRoleNote(String roleNote) {
		this.roleNote = roleNote == null ? null : roleNote.trim();
	}
}