package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class Room extends Model {

	/**
	 * 自增Id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 楼栋Id
	 * @mbggenerated
	 */
	private Long buildingId;
	/**
	 * 楼层号
	 * @mbggenerated
	 */
	private String floor;
	/**
	 * 单元类型
	 * @mbggenerated
	 */
	private String unit;
	/**
	 * 房间号
	 * @mbggenerated
	 */
	private String roomNo;
	/**
	 * 紧急联系人
	 * @mbggenerated
	 */
	private String contactPeople;
	/**
	 * 紧急联系人电话
	 * @mbggenerated
	 */
	private String contactPhone;
	/**
	 * 备注
	 * @mbggenerated
	 */
	private String note;
	/**
	 * 物业系统的房间编号
	 * @mbggenerated
	 */
	private String unitNo;
	/**
	 * 添加时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 修改时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.id
	 * @return  the value of n_room.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增Id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.id
	 * @param id  the value for n_room.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.building_id
	 * @return  the value of n_room.building_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "楼栋Id")
	public Long getBuildingId() {
		return buildingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.building_id
	 * @param buildingId  the value for n_room.building_id
	 * @mbggenerated
	 */
	public void setBuildingId(Long buildingId) {
		this.buildingId = buildingId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.floor
	 * @return  the value of n_room.floor
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "楼层号")
	public String getFloor() {
		return floor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.floor
	 * @param floor  the value for n_room.floor
	 * @mbggenerated
	 */
	public void setFloor(String floor) {
		this.floor = floor == null ? null : floor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.unit
	 * @return  the value of n_room.unit
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "单元类型")
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.unit
	 * @param unit  the value for n_room.unit
	 * @mbggenerated
	 */
	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.room_no
	 * @return  the value of n_room.room_no
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "房间号")
	public String getRoomNo() {
		return roomNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.room_no
	 * @param roomNo  the value for n_room.room_no
	 * @mbggenerated
	 */
	public void setRoomNo(String roomNo) {
		this.roomNo = roomNo == null ? null : roomNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.contact_people
	 * @return  the value of n_room.contact_people
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "紧急联系人")
	public String getContactPeople() {
		return contactPeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.contact_people
	 * @param contactPeople  the value for n_room.contact_people
	 * @mbggenerated
	 */
	public void setContactPeople(String contactPeople) {
		this.contactPeople = contactPeople == null ? null : contactPeople
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.contact_phone
	 * @return  the value of n_room.contact_phone
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "紧急联系人电话")
	public String getContactPhone() {
		return contactPhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.contact_phone
	 * @param contactPhone  the value for n_room.contact_phone
	 * @mbggenerated
	 */
	public void setContactPhone(String contactPhone) {
		this.contactPhone = contactPhone == null ? null : contactPhone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.note
	 * @return  the value of n_room.note
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "备注")
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.note
	 * @param note  the value for n_room.note
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.unit_no
	 * @return  the value of n_room.unit_no
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "物业系统的房间编号")
	public String getUnitNo() {
		return unitNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.unit_no
	 * @param unitNo  the value for n_room.unit_no
	 * @mbggenerated
	 */
	public void setUnitNo(String unitNo) {
		this.unitNo = unitNo == null ? null : unitNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.row_add_time
	 * @return  the value of n_room.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "添加时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.row_add_time
	 * @param rowAddTime  the value for n_room.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_room.row_update_time
	 * @return  the value of n_room.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "修改时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_room.row_update_time
	 * @param rowUpdateTime  the value for n_room.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}
}