package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class Scheduling extends Model {
    /**
     * 自增id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * 排班人id
     *
     * @mbggenerated
     */
    private Long schedulingUserId;

    /**
     * 值班人id
     *
     * @mbggenerated
     */
    private Long suserId;

    /**
     * 值班小区id
     *
     * @mbggenerated
     */
    private Long communityId;

    /**
     * 值班楼层id
     *
     * @mbggenerated
     */
    private Long buildingId;

    /**
     * 值班开始时间
     *
     * @mbggenerated
     */
    private Date dutyStartTime;

    /**
     * 值班结束时间
     *
     * @mbggenerated
     */
    private Date dutyEndTime;

    /**
     * 添加时间
     *
     * @mbggenerated
     */
    private Date rowAddTime;

    /**
     * 更新时间
     *
     * @mbggenerated
     */
    private Date rowUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_scheduling.id
     *
     * @return the value of n_scheduling.id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "自增id")
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_scheduling.id
     *
     * @param id the value for n_scheduling.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_scheduling.scheduling_user_id
     *
     * @return the value of n_scheduling.scheduling_user_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "排班人id")
    public Long getSchedulingUserId() {
        return schedulingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_scheduling.scheduling_user_id
     *
     * @param schedulingUserId the value for n_scheduling.scheduling_user_id
     *
     * @mbggenerated
     */
    public void setSchedulingUserId(Long schedulingUserId) {
        this.schedulingUserId = schedulingUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_scheduling.suser_id
     *
     * @return the value of n_scheduling.suser_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "值班人id")
    public Long getSuserId() {
        return suserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_scheduling.suser_id
     *
     * @param suserId the value for n_scheduling.suser_id
     *
     * @mbggenerated
     */
    public void setSuserId(Long suserId) {
        this.suserId = suserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_scheduling.community_id
     *
     * @return the value of n_scheduling.community_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "值班小区id")
    public Long getCommunityId() {
        return communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_scheduling.community_id
     *
     * @param communityId the value for n_scheduling.community_id
     *
     * @mbggenerated
     */
    public void setCommunityId(Long communityId) {
        this.communityId = communityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_scheduling.building_id
     *
     * @return the value of n_scheduling.building_id
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "值班楼层id")
    public Long getBuildingId() {
        return buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_scheduling.building_id
     *
     * @param buildingId the value for n_scheduling.building_id
     *
     * @mbggenerated
     */
    public void setBuildingId(Long buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_scheduling.duty_start_time
     *
     * @return the value of n_scheduling.duty_start_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "值班开始时间")
    public Date getDutyStartTime() {
        return dutyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_scheduling.duty_start_time
     *
     * @param dutyStartTime the value for n_scheduling.duty_start_time
     *
     * @mbggenerated
     */
    public void setDutyStartTime(Date dutyStartTime) {
        this.dutyStartTime = dutyStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_scheduling.duty_end_time
     *
     * @return the value of n_scheduling.duty_end_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "值班结束时间")
    public Date getDutyEndTime() {
        return dutyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_scheduling.duty_end_time
     *
     * @param dutyEndTime the value for n_scheduling.duty_end_time
     *
     * @mbggenerated
     */
    public void setDutyEndTime(Date dutyEndTime) {
        this.dutyEndTime = dutyEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_scheduling.row_add_time
     *
     * @return the value of n_scheduling.row_add_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "添加时间")
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_scheduling.row_add_time
     *
     * @param rowAddTime the value for n_scheduling.row_add_time
     *
     * @mbggenerated
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column n_scheduling.row_update_time
     *
     * @return the value of n_scheduling.row_update_time
     *
     * @mbggenerated
     */
    @ApiModelProperty(value = "更新时间")
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column n_scheduling.row_update_time
     *
     * @param rowUpdateTime the value for n_scheduling.row_update_time
     *
     * @mbggenerated
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }
}