package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

public class ServiceClockRoleConfig extends Model implements Serializable{

	/**
	 * 自增id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 角色，1管家，2保安，3维修人员，4调度人员
	 * @mbggenerated
	 */
	private Integer role;
	/**
	 * 经度中心点
	 * @mbggenerated
	 */
	private Double longitude;
	/**
	 * 纬度中心点
	 * @mbggenerated
	 */
	private Double latitude;
	/**
	 * 有效距离,单位(米)
	 * @mbggenerated
	 */
	private Double distance;
	/**
	 * 上班打卡时间(只取时分秒)
	 * @mbggenerated
	 */
	private Date clockInTime;
	/**
	 * 下班打卡时间(只取时分秒)
	 * @mbggenerated
	 */
	private Date clockOutTime;
	/**
	 * 添加时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 数据库更新时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;
	/**
	 * @mbggenerated
	 */
	private Long communityId;
	/**
	 * 上班打卡有效延后时间,单位(小时),如果超出这个范围,就是迟到
	 * @mbggenerated
	 */
	private Double inInterval;
	/**
	 * 下班打卡有效提前时间,单位(小时),如果超出这个范围,就是早退
	 * @mbggenerated
	 */
	private Double outInterval;
	/**
	 * 是否允许外勤打卡,0:不允许,1：允许
	 * @mbggenerated
	 */
	private Integer allowOutside;
	/**
	 * 地区的名称
	 * @mbggenerated
	 */
	private String region;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.id
	 * @return  the value of n_service_clock_role_config.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.id
	 * @param id  the value for n_service_clock_role_config.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.role
	 * @return  the value of n_service_clock_role_config.role
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "角色，1管家，2保安，3维修人员，4调度人员")
	public Integer getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.role
	 * @param role  the value for n_service_clock_role_config.role
	 * @mbggenerated
	 */
	public void setRole(Integer role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.longitude
	 * @return  the value of n_service_clock_role_config.longitude
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "经度中心点")
	public Double getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.longitude
	 * @param longitude  the value for n_service_clock_role_config.longitude
	 * @mbggenerated
	 */
	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.latitude
	 * @return  the value of n_service_clock_role_config.latitude
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "纬度中心点")
	public Double getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.latitude
	 * @param latitude  the value for n_service_clock_role_config.latitude
	 * @mbggenerated
	 */
	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.distance
	 * @return  the value of n_service_clock_role_config.distance
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "有效距离,单位(米)")
	public Double getDistance() {
		return distance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.distance
	 * @param distance  the value for n_service_clock_role_config.distance
	 * @mbggenerated
	 */
	public void setDistance(Double distance) {
		this.distance = distance;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.clock_in_time
	 * @return  the value of n_service_clock_role_config.clock_in_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "上班打卡时间(只取时分秒)")
	public Date getClockInTime() {
		return clockInTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.clock_in_time
	 * @param clockInTime  the value for n_service_clock_role_config.clock_in_time
	 * @mbggenerated
	 */
	public void setClockInTime(Date clockInTime) {
		this.clockInTime = clockInTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.clock_out_time
	 * @return  the value of n_service_clock_role_config.clock_out_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "下班打卡时间(只取时分秒)")
	public Date getClockOutTime() {
		return clockOutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.clock_out_time
	 * @param clockOutTime  the value for n_service_clock_role_config.clock_out_time
	 * @mbggenerated
	 */
	public void setClockOutTime(Date clockOutTime) {
		this.clockOutTime = clockOutTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.row_add_time
	 * @return  the value of n_service_clock_role_config.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "添加时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.row_add_time
	 * @param rowAddTime  the value for n_service_clock_role_config.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.row_update_time
	 * @return  the value of n_service_clock_role_config.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "数据库更新时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.row_update_time
	 * @param rowUpdateTime  the value for n_service_clock_role_config.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.community_id
	 * @return  the value of n_service_clock_role_config.community_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	public Long getCommunityId() {
		return communityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.community_id
	 * @param communityId  the value for n_service_clock_role_config.community_id
	 * @mbggenerated
	 */
	public void setCommunityId(Long communityId) {
		this.communityId = communityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.in_interval
	 * @return  the value of n_service_clock_role_config.in_interval
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "上班打卡有效延后时间,单位(小时),如果超出这个范围,就是迟到")
	public Double getInInterval() {
		return inInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.in_interval
	 * @param inInterval  the value for n_service_clock_role_config.in_interval
	 * @mbggenerated
	 */
	public void setInInterval(Double inInterval) {
		this.inInterval = inInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.out_interval
	 * @return  the value of n_service_clock_role_config.out_interval
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "下班打卡有效提前时间,单位(小时),如果超出这个范围,就是早退")
	public Double getOutInterval() {
		return outInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.out_interval
	 * @param outInterval  the value for n_service_clock_role_config.out_interval
	 * @mbggenerated
	 */
	public void setOutInterval(Double outInterval) {
		this.outInterval = outInterval;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.allow_outside
	 * @return  the value of n_service_clock_role_config.allow_outside
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "是否允许外勤打卡,0:不允许,1：允许")
	public Integer getAllowOutside() {
		return allowOutside;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.allow_outside
	 * @param allowOutside  the value for n_service_clock_role_config.allow_outside
	 * @mbggenerated
	 */
	public void setAllowOutside(Integer allowOutside) {
		this.allowOutside = allowOutside;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_service_clock_role_config.region
	 * @return  the value of n_service_clock_role_config.region
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "地区的名称")
	public String getRegion() {
		return region;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_service_clock_role_config.region
	 * @param region  the value for n_service_clock_role_config.region
	 * @mbggenerated
	 */
	public void setRegion(String region) {
		this.region = region == null ? null : region.trim();
	}
}