package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.ModelExample;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserWebmasterMessageExample extends ModelExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public UserWebmasterMessageExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public Criteria getCriteria() {
		if (oredCriteria.size() == 0) {
			createCriteria();
		}
		return oredCriteria.get(0);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	public void addCriteria(List<Criterion> criteria) {
		getCriteria().getCriteria().addAll(criteria);
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table n_user_webmaster_message
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;
		private boolean ignoreNull;

		private boolean isIgnoreNull() {
			return ignoreNull;
		}

		public Criteria ignoreNull() {
			this.ignoreNull = true;
			return (Criteria) this;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException(
							"Value for condition cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition));
			}
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException("Value for " + property
							+ " cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition, value));
			}
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				if (!isIgnoreNull()) {
					throw new RuntimeException("Between values for " + property
							+ " cannot be null");
				}
			} else {
				criteria.add(new Criterion(condition, value1, value2));
			}
		}

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdIsNull() {
			addCriterion("buser_send_id is null");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdIsNotNull() {
			addCriterion("buser_send_id is not null");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdEqualTo(Long value) {
			addCriterion("buser_send_id =", value, "buserSendId");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdNotEqualTo(Long value) {
			addCriterion("buser_send_id <>", value, "buserSendId");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdGreaterThan(Long value) {
			addCriterion("buser_send_id >", value, "buserSendId");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdGreaterThanOrEqualTo(Long value) {
			addCriterion("buser_send_id >=", value, "buserSendId");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdLessThan(Long value) {
			addCriterion("buser_send_id <", value, "buserSendId");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdLessThanOrEqualTo(Long value) {
			addCriterion("buser_send_id <=", value, "buserSendId");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdIn(List<Long> values) {
			addCriterion("buser_send_id in", values, "buserSendId");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdNotIn(List<Long> values) {
			addCriterion("buser_send_id not in", values, "buserSendId");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdBetween(Long value1, Long value2) {
			addCriterion("buser_send_id between", value1, value2, "buserSendId");
			return (Criteria) this;
		}

		public Criteria andBuserSendIdNotBetween(Long value1, Long value2) {
			addCriterion("buser_send_id not between", value1, value2,
					"buserSendId");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdIsNull() {
			addCriterion("buser_receive_id is null");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdIsNotNull() {
			addCriterion("buser_receive_id is not null");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdEqualTo(Long value) {
			addCriterion("buser_receive_id =", value, "buserReceiveId");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdNotEqualTo(Long value) {
			addCriterion("buser_receive_id <>", value, "buserReceiveId");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdGreaterThan(Long value) {
			addCriterion("buser_receive_id >", value, "buserReceiveId");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdGreaterThanOrEqualTo(Long value) {
			addCriterion("buser_receive_id >=", value, "buserReceiveId");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdLessThan(Long value) {
			addCriterion("buser_receive_id <", value, "buserReceiveId");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdLessThanOrEqualTo(Long value) {
			addCriterion("buser_receive_id <=", value, "buserReceiveId");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdIn(List<Long> values) {
			addCriterion("buser_receive_id in", values, "buserReceiveId");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdNotIn(List<Long> values) {
			addCriterion("buser_receive_id not in", values, "buserReceiveId");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdBetween(Long value1, Long value2) {
			addCriterion("buser_receive_id between", value1, value2,
					"buserReceiveId");
			return (Criteria) this;
		}

		public Criteria andBuserReceiveIdNotBetween(Long value1, Long value2) {
			addCriterion("buser_receive_id not between", value1, value2,
					"buserReceiveId");
			return (Criteria) this;
		}

		public Criteria andContentIdIsNull() {
			addCriterion("content_id is null");
			return (Criteria) this;
		}

		public Criteria andContentIdIsNotNull() {
			addCriterion("content_id is not null");
			return (Criteria) this;
		}

		public Criteria andContentIdEqualTo(Long value) {
			addCriterion("content_id =", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdNotEqualTo(Long value) {
			addCriterion("content_id <>", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdGreaterThan(Long value) {
			addCriterion("content_id >", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdGreaterThanOrEqualTo(Long value) {
			addCriterion("content_id >=", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdLessThan(Long value) {
			addCriterion("content_id <", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdLessThanOrEqualTo(Long value) {
			addCriterion("content_id <=", value, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdIn(List<Long> values) {
			addCriterion("content_id in", values, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdNotIn(List<Long> values) {
			addCriterion("content_id not in", values, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdBetween(Long value1, Long value2) {
			addCriterion("content_id between", value1, value2, "contentId");
			return (Criteria) this;
		}

		public Criteria andContentIdNotBetween(Long value1, Long value2) {
			addCriterion("content_id not between", value1, value2, "contentId");
			return (Criteria) this;
		}

		public Criteria andSendTypeIsNull() {
			addCriterion("send_type is null");
			return (Criteria) this;
		}

		public Criteria andSendTypeIsNotNull() {
			addCriterion("send_type is not null");
			return (Criteria) this;
		}

		public Criteria andSendTypeEqualTo(Integer value) {
			addCriterion("send_type =", value, "sendType");
			return (Criteria) this;
		}

		public Criteria andSendTypeNotEqualTo(Integer value) {
			addCriterion("send_type <>", value, "sendType");
			return (Criteria) this;
		}

		public Criteria andSendTypeGreaterThan(Integer value) {
			addCriterion("send_type >", value, "sendType");
			return (Criteria) this;
		}

		public Criteria andSendTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("send_type >=", value, "sendType");
			return (Criteria) this;
		}

		public Criteria andSendTypeLessThan(Integer value) {
			addCriterion("send_type <", value, "sendType");
			return (Criteria) this;
		}

		public Criteria andSendTypeLessThanOrEqualTo(Integer value) {
			addCriterion("send_type <=", value, "sendType");
			return (Criteria) this;
		}

		public Criteria andSendTypeIn(List<Integer> values) {
			addCriterion("send_type in", values, "sendType");
			return (Criteria) this;
		}

		public Criteria andSendTypeNotIn(List<Integer> values) {
			addCriterion("send_type not in", values, "sendType");
			return (Criteria) this;
		}

		public Criteria andSendTypeBetween(Integer value1, Integer value2) {
			addCriterion("send_type between", value1, value2, "sendType");
			return (Criteria) this;
		}

		public Criteria andSendTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("send_type not between", value1, value2, "sendType");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andMessageTypeIsNull() {
			addCriterion("message_type is null");
			return (Criteria) this;
		}

		public Criteria andMessageTypeIsNotNull() {
			addCriterion("message_type is not null");
			return (Criteria) this;
		}

		public Criteria andMessageTypeEqualTo(Integer value) {
			addCriterion("message_type =", value, "messageType");
			return (Criteria) this;
		}

		public Criteria andMessageTypeNotEqualTo(Integer value) {
			addCriterion("message_type <>", value, "messageType");
			return (Criteria) this;
		}

		public Criteria andMessageTypeGreaterThan(Integer value) {
			addCriterion("message_type >", value, "messageType");
			return (Criteria) this;
		}

		public Criteria andMessageTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("message_type >=", value, "messageType");
			return (Criteria) this;
		}

		public Criteria andMessageTypeLessThan(Integer value) {
			addCriterion("message_type <", value, "messageType");
			return (Criteria) this;
		}

		public Criteria andMessageTypeLessThanOrEqualTo(Integer value) {
			addCriterion("message_type <=", value, "messageType");
			return (Criteria) this;
		}

		public Criteria andMessageTypeIn(List<Integer> values) {
			addCriterion("message_type in", values, "messageType");
			return (Criteria) this;
		}

		public Criteria andMessageTypeNotIn(List<Integer> values) {
			addCriterion("message_type not in", values, "messageType");
			return (Criteria) this;
		}

		public Criteria andMessageTypeBetween(Integer value1, Integer value2) {
			addCriterion("message_type between", value1, value2, "messageType");
			return (Criteria) this;
		}

		public Criteria andMessageTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("message_type not between", value1, value2,
					"messageType");
			return (Criteria) this;
		}

		public Criteria andContentIsNull() {
			addCriterion("content is null");
			return (Criteria) this;
		}

		public Criteria andContentIsNotNull() {
			addCriterion("content is not null");
			return (Criteria) this;
		}

		public Criteria andContentEqualTo(String value) {
			addCriterion("content =", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotEqualTo(String value) {
			addCriterion("content <>", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThan(String value) {
			addCriterion("content >", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentGreaterThanOrEqualTo(String value) {
			addCriterion("content >=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThan(String value) {
			addCriterion("content <", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLessThanOrEqualTo(String value) {
			addCriterion("content <=", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentLike(String value) {
			addCriterion("content like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotLike(String value) {
			addCriterion("content not like", value, "content");
			return (Criteria) this;
		}

		public Criteria andContentIn(List<String> values) {
			addCriterion("content in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotIn(List<String> values) {
			addCriterion("content not in", values, "content");
			return (Criteria) this;
		}

		public Criteria andContentBetween(String value1, String value2) {
			addCriterion("content between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andContentNotBetween(String value1, String value2) {
			addCriterion("content not between", value1, value2, "content");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeIsNull() {
			addCriterion("row_add_time is null");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeIsNotNull() {
			addCriterion("row_add_time is not null");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeEqualTo(Date value) {
			addCriterion("row_add_time =", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeNotEqualTo(Date value) {
			addCriterion("row_add_time <>", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeGreaterThan(Date value) {
			addCriterion("row_add_time >", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("row_add_time >=", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeLessThan(Date value) {
			addCriterion("row_add_time <", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeLessThanOrEqualTo(Date value) {
			addCriterion("row_add_time <=", value, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeIn(List<Date> values) {
			addCriterion("row_add_time in", values, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeNotIn(List<Date> values) {
			addCriterion("row_add_time not in", values, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeBetween(Date value1, Date value2) {
			addCriterion("row_add_time between", value1, value2, "rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowAddTimeNotBetween(Date value1, Date value2) {
			addCriterion("row_add_time not between", value1, value2,
					"rowAddTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeIsNull() {
			addCriterion("row_update_time is null");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeIsNotNull() {
			addCriterion("row_update_time is not null");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeEqualTo(Date value) {
			addCriterion("row_update_time =", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeNotEqualTo(Date value) {
			addCriterion("row_update_time <>", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeGreaterThan(Date value) {
			addCriterion("row_update_time >", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("row_update_time >=", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeLessThan(Date value) {
			addCriterion("row_update_time <", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("row_update_time <=", value, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeIn(List<Date> values) {
			addCriterion("row_update_time in", values, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeNotIn(List<Date> values) {
			addCriterion("row_update_time not in", values, "rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("row_update_time between", value1, value2,
					"rowUpdateTime");
			return (Criteria) this;
		}

		public Criteria andRowUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("row_update_time not between", value1, value2,
					"rowUpdateTime");
			return (Criteria) this;
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table n_user_webmaster_message
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}