package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class LectureHallIntroducing extends Model {

	/**
	 * 自增id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 业主id
	 * @mbggenerated
	 */
	private Long buserId;
	/**
	 * @mbggenerated
	 */
	private Long communityId;
	/**
	 * 话题,标题
	 * @mbggenerated
	 */
	private String title;
	/**
	 * 内容大纲
	 * @mbggenerated
	 */
	private String content;
	/**
	 * 姓名
	 * @mbggenerated
	 */
	private String name;
	/**
	 * 电话
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * 个人介绍
	 * @mbggenerated
	 */
	private String description;
	/**
	 * 报名时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 更新时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lecture_hall_introducing.id
	 * @return  the value of n_lecture_hall_introducing.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lecture_hall_introducing.id
	 * @param id  the value for n_lecture_hall_introducing.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lecture_hall_introducing.buser_id
	 * @return  the value of n_lecture_hall_introducing.buser_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "业主id")
	public Long getBuserId() {
		return buserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lecture_hall_introducing.buser_id
	 * @param buserId  the value for n_lecture_hall_introducing.buser_id
	 * @mbggenerated
	 */
	public void setBuserId(Long buserId) {
		this.buserId = buserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lecture_hall_introducing.community_id
	 * @return  the value of n_lecture_hall_introducing.community_id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "")
	public Long getCommunityId() {
		return communityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lecture_hall_introducing.community_id
	 * @param communityId  the value for n_lecture_hall_introducing.community_id
	 * @mbggenerated
	 */
	public void setCommunityId(Long communityId) {
		this.communityId = communityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lecture_hall_introducing.title
	 * @return  the value of n_lecture_hall_introducing.title
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "话题,标题")
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lecture_hall_introducing.title
	 * @param title  the value for n_lecture_hall_introducing.title
	 * @mbggenerated
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lecture_hall_introducing.content
	 * @return  the value of n_lecture_hall_introducing.content
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "内容大纲")
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lecture_hall_introducing.content
	 * @param content  the value for n_lecture_hall_introducing.content
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lecture_hall_introducing.name
	 * @return  the value of n_lecture_hall_introducing.name
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "姓名")
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lecture_hall_introducing.name
	 * @param name  the value for n_lecture_hall_introducing.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lecture_hall_introducing.phone
	 * @return  the value of n_lecture_hall_introducing.phone
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "电话")
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lecture_hall_introducing.phone
	 * @param phone  the value for n_lecture_hall_introducing.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lecture_hall_introducing.description
	 * @return  the value of n_lecture_hall_introducing.description
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "个人介绍")
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lecture_hall_introducing.description
	 * @param description  the value for n_lecture_hall_introducing.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lecture_hall_introducing.row_add_time
	 * @return  the value of n_lecture_hall_introducing.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "报名时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lecture_hall_introducing.row_add_time
	 * @param rowAddTime  the value for n_lecture_hall_introducing.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lecture_hall_introducing.row_update_time
	 * @return  the value of n_lecture_hall_introducing.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "更新时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lecture_hall_introducing.row_update_time
	 * @param rowUpdateTime  the value for n_lecture_hall_introducing.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}
}