package com.bola.nwcl.dal.mybatis.model;

import com.bola.nwcl.common.mybatis.model.Model;
import com.wordnik.swagger.annotations.ApiModelProperty;
import java.util.Date;

public class LinglingManager extends Model {

	/**
	 * 自增Id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * 工程人员登陆账号
	 * @mbggenerated
	 */
	private String account;
	/**
	 * 工程人员显示名称
	 * @mbggenerated
	 */
	private String name;
	/**
	 * 工程人员登陆密码
	 * @mbggenerated
	 */
	private String password;
	/**
	 * 用于工程人员修改、找回密码
	 * @mbggenerated
	 */
	private String mobilephone;
	/**
	 * 备注
	 * @mbggenerated
	 */
	private String note;
	/**
	 * 添加时间
	 * @mbggenerated
	 */
	private Date rowAddTime;
	/**
	 * 修改时间
	 * @mbggenerated
	 */
	private Date rowUpdateTime;
	/**
	 * 工程人员账号ID（工程人员标志位，后续接口使用）
	 * @mbggenerated
	 */
	private String userid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_manager.id
	 * @return  the value of n_lingling_manager.id
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "自增Id")
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_manager.id
	 * @param id  the value for n_lingling_manager.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_manager.account
	 * @return  the value of n_lingling_manager.account
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "工程人员登陆账号")
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_manager.account
	 * @param account  the value for n_lingling_manager.account
	 * @mbggenerated
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_manager.name
	 * @return  the value of n_lingling_manager.name
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "工程人员显示名称")
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_manager.name
	 * @param name  the value for n_lingling_manager.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_manager.password
	 * @return  the value of n_lingling_manager.password
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "工程人员登陆密码")
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_manager.password
	 * @param password  the value for n_lingling_manager.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_manager.mobilePhone
	 * @return  the value of n_lingling_manager.mobilePhone
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "用于工程人员修改、找回密码")
	public String getMobilephone() {
		return mobilephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_manager.mobilePhone
	 * @param mobilephone  the value for n_lingling_manager.mobilePhone
	 * @mbggenerated
	 */
	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone == null ? null : mobilephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_manager.note
	 * @return  the value of n_lingling_manager.note
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "备注")
	public String getNote() {
		return note;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_manager.note
	 * @param note  the value for n_lingling_manager.note
	 * @mbggenerated
	 */
	public void setNote(String note) {
		this.note = note == null ? null : note.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_manager.row_add_time
	 * @return  the value of n_lingling_manager.row_add_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "添加时间")
	public Date getRowAddTime() {
		return rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_manager.row_add_time
	 * @param rowAddTime  the value for n_lingling_manager.row_add_time
	 * @mbggenerated
	 */
	public void setRowAddTime(Date rowAddTime) {
		this.rowAddTime = rowAddTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_manager.row_update_time
	 * @return  the value of n_lingling_manager.row_update_time
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "修改时间")
	public Date getRowUpdateTime() {
		return rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_manager.row_update_time
	 * @param rowUpdateTime  the value for n_lingling_manager.row_update_time
	 * @mbggenerated
	 */
	public void setRowUpdateTime(Date rowUpdateTime) {
		this.rowUpdateTime = rowUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column n_lingling_manager.userId
	 * @return  the value of n_lingling_manager.userId
	 * @mbggenerated
	 */
	@ApiModelProperty(value = "工程人员账号ID（工程人员标志位，后续接口使用）")
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column n_lingling_manager.userId
	 * @param userid  the value for n_lingling_manager.userId
	 * @mbggenerated
	 */
	public void setUserid(String userid) {
		this.userid = userid == null ? null : userid.trim();
	}
}